### PR TITLE
Fix team page

### LINKED ISSUE #157: Make sponsor size vary with tier
Higher paying tiers should have a bigger banner than lower paying tiers.

### PR DESCRIPTION
**Pull request by toni-santos**
Remove the border on the team page, and other tweaks.

### CODE REVIEW

File: resources/js/Components/Navbar.vue
Comment (Naapperas) [inline resources/js/Components/Navbar.vue:1]: You should add `preserve-state` to the Link component in DropdownLink. It will fix the page reload problem where a smooth-scroll "starts from scratch".

File: resources/js/Pages/Home.vue [hunk 1]
```diff
@@ -63,6 +63,13 @@ const formattedDate = (
 
 <template>
     <AppLayout title="Home">
+        <a
+            v-if="canEnroll"
+            href="#enroll-wrapper"
+            class="group fixed bottom-10 right-12 z-50 cursor-pointer border border-black bg-2023-red-dark p-2 font-bold text-white shadow shadow-2023-teal"
+        >
+            Inscreve-te<v-icon name="io-chevron-down" fill="white"></v-icon>
```
Comment (Naapperas) [inline resources/js/Pages/Home.vue]: This icon should be an arrow, this might confuse people into thinking this is a dropdown.

**Review by Naapperas — CHANGES_REQUESTED** [review]
LGTM

**Review by pedronunes19 — DISMISSED** [review]

**Review by Naapperas — APPROVED** [review]
